### ISSUE TITLE
Data description - research question 1

### ISSUE THREAD

**Issue by Thanh-8213** [etc5521-2020/assignment-1-cassowary#3]
Hello Weihao,

I will need your opinion following details: 
Regarding question 1
1. What were the characteristics of GDPR fines across countries, time and corporations? **Did certain countries target certain corporations at certain time?**

Do you think the bold part should be included?  I do not think it is related and make sense.

Vodafone seems to be the target of Spain, but I do not think it is make too much sense.

**Comment by TengMCing** [comment]
Yes, you are right. My initial thought, when written down this question, was if GDPR was used as a tool against non-local IT companies in the EU, such as Google and Vodafone. It's because they are struggling in an IT war.

We can actually modify the question to be "Did certain corporations being targeted by GDPR authorities?"

**Comment by Thanh-8213** [comment]
Except Vodafone, I don't see any pattern there. I can't really write for it as it is pretty strange to me
